spring:
  application:
    name: virtualpets-server-springboot
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      schema: virtualpets_server_springboot
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        default_schema: virtualpets_server_springboot
        show_sql: 'true'
        max_fetch_depth: 3
        jdbc:
          fetch_size: 50
          batch_size: 10
        use_nationalized_character_data: 'true'
        connection:
          CharSet: utf8
          characterEncoding: utf8
          useUnicode: 'true'
        implicit_naming_strategy: default

  liquibase:
    default-schema: virtualpets_server_springboot
#spring.mail.host=localhost
#spring.mail.port=8888
#spring.mail.username=test
#spring.mail.password=test
logging:
  level:
    root : warn
  file:
    name: virtualpets_server_springboot.log
    path: logs
#  logback:
#    rollingpolicy:
#      file-name-pattern: virtualpets_server_springboot.%d{yyyy-MM-dd}.%i.gz
#      max-file-size: 6MB
#      total-size-cap: 100MB
#      max-history: 3
virtualpets-server-springboot:
  version: 0.21
  servers:
   - url: http://localhost:8080
     name: Русскоязычный основной
     locale: ru
   - url: broken_test
     name: broken_test
     locale: broken_test
  mail:
    from: noemail@nowhere.com
    subject: Recover password






