apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: virtualpets-server-springboot
  name: virtualpets-server-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtualpets-server-springboot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: virtualpets-server-springboot
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: virtualpets-config
              key: SPRING_DATASOURCE_URL
        - name: DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: virtualpets-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: virtualpets-config
              key: SPRING_DATASOURCE_PASSWORD
        image: urvanovru/virtualpets-server-springboot
        name: virtualpets-server-springboot
        imagePullPolicy: Never
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: virtualpets-server-springboot
  name: virtualpets-server-springboot
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: virtualpets-server-springboot
  type: ClusterIP
status:
  loadBalancer: {}
